### ISSUE TITLE
Entity being ticked; rebornmod:entities.othnielia

### ISSUE THREAD

**Issue by Zapzatron** [Interactive-Modding/JurassicWorldRebornMod#67]
Some time after loading a chunk, the server crashes.

Logs:
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  Inventory Tweaks Coremod (inventorytweaks-1.64dev.151.jar)
  CTMCorePlugin (ctm-mc1.12.2-1.0.2.31.jar)
  CoreMod (aroma1997core-1.12.2-2.0.0.2.b167.jar)
  UniDictCoreMod (unidict-1.12.2-3.0.10.jar)
  HCASM (hammerlib-1.12.2-2.0.6.32.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 7/29/23 10:34 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.pathfinding.PathHeap.func_75846_b(SourceFile:107)
	at net.minecraft.pathfinding.PathHeap.func_75844_c(SourceFile:40)
	at net.minecraft.pathfinding.PathFinder.func_186335_a(SourceFile:66)
	at net.minecraft.pathfinding.PathFinder.func_186334_a(SourceFile:40)
	at net.minecraft.pathfinding.PathFinder.func_186336_a(SourceFile:30)
	at net.minecraft.pathfinding.PathNavigate.func_179680_a(PathNavigate.java:119)
	at net.minecraft.pathfinding.PathNavigateGround.func_179680_a(SourceFile:68)
	at net.minecraft.pathfinding.PathNavigateGround.func_75494_a(SourceFile:73)
	at net.minecraft.pathfinding.PathNavigate.func_75497_a(PathNavigate.java:163)
	at mod.reborn.server.entity.ai.Relationship.update(Relationship.java:38)
	at mod.reborn.server.entity.DinosaurEntity.func_70636_d(DinosaurEntity.java:1041)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2509)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:318)
	at mod.reborn.server.entity.DinosaurEntity.func_70071_h_(DinosaurEntity.java:1089)
	at net.minecraft.world.World.func_72866_a(World.java:2329)
	at net.minecraft.world.World.func_72870_g(World.java:2283)
	at net.minecraft.world.World.func_72939_s(World.java:2065)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:852)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:923)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:800)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:672)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.pathfinding.PathHeap.func_75846_b(SourceFile:107)
	at net.minecraft.pathfinding.PathHeap.func_75844_c(SourceFile:40)
	at net.minecraft.pathfinding.PathFinder.func_186335_a(SourceFile:66)
	at net.minecraft.pathfinding.PathFinder.func_186334_a(SourceFile:40)
	at net.minecraft.pathfinding.PathFinder.func_186336_a(SourceFile:30)
	at net.minecraft.pathfinding.PathNavigate.func_179680_a(PathNavigate.java:119)
	at net.minecraft.pathfinding.PathNavigateGround.func_179680_a(SourceFile:68)
	at net.minecraft.pathfinding.PathNavigateGround.func_75494_a(SourceFile:73)
	at net.minecraft.pathfinding.PathNavigate.func_75497_a(PathNavigate.java:163)
	at mod.reborn.server.entity.ai.Relationship.update(Relationship.java:38)
	at mod.reborn.server.entity.DinosaurEntity.func_70636_d(DinosaurEntity.java:1041)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2509)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:318)
	at mod.reborn.server.entity.DinosaurEntity.func_70071_h_(DinosaurEntity.java:1089)
	at net.minecraft.world.World.func_72866_a(World.java:2329)
	at net.minecraft.world.World.func_72870_g(World.java:2283)

-- Entity being ticked --
Details:
	Entity Type: rebornmod:entities.othnielia (mod.reborn.server.entity.dinosaur.OthnieliaEntity)
	Entity ID: 952
	Entity Name: Othnielia
	Entity's Exact location: 3127.24, 62.32, 64.25
	Entity's Block location: World: (3127,62,64), Chunk: (at 7,3,0 in 195,4; contains blocks 3120,0,64 to 3135,255,79), Region: (6,0; contains chunks 192,0 to 223,31, blocks 3072,0,0 to 3583,255,511)
	Entity's Momentum: 0.00, -0.02, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:2065)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:852)

-- Affected level --
Details:
	Level name: Test_World
	All players: 1 total; [EntityPlayerMP['Test'/755, uuid='beb5d4c7-781c-3b1f-89bc-f9e5f467a1d6', l='Test_World', x=3141.71, y=64.00, z=6.81, cx=196, cd=0, tl=2943419, v=true, d=false](Test at 3141.713263661995,64.0,6.812398196834397)]
	Chunk stats: ServerChunkCache: 841 Drop: 0
	Level seed: -2960788715385653579
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-12,64,232), Chunk: (at 4,4,8 in -1,14; contains blocks -16,0,224 to -1,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 3606145 game time, 4519535 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 76502 (now: false), thunder time: 104152 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:923)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:800)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:672)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Magma Version: 1.12.2-15ea32c3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_341, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6064668072 bytes (5783 MB) / 10317463552 bytes (9839 MB) up to 10317463552 bytes (9839 MB)
	JVM Flags: 2 total; -Xms10000M -Xmx10000M
	IntCache: cache: 1, tcache: 2, allocated: 14, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 89 mods loaded, 89 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                | Version              | Source                                             | Signature                                |
	|:------ |:--------------------------------- |:-------------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                         | 1.12.2               | minecraft.jar                                      | None                                     |
	| LCHIJA | mcp                               | 9.42                 | minecraft.jar                                      | None                                     |
	| LCHIJA | FML                               | 8.0.99.99            | Magma_Server.jar                                   | None                                     |
	| LCHIJA | forge                             | 14.23.5.2860         | Magma_Server.jar                                   | None                                     |
	| LCHIJA | quarryplus                        | 12.5.7               | AdditionalEnchantedMiner-1.12.2-12.5.7.jar         | 617a4e95f0af9de5402bb9883abe0f53a6bfa230 |
	| LCHIJA | quarryplus_ct                     | 12.5.7               | AdditionalEnchantedMiner-1.12.2-12.5.7.jar         | 617a4e95f0af9de5402bb9883abe0f53a6bfa230 |
	| LCHIJA | appliedenergistics2               | rv6-stable-7         | appliedenergistics2-rv6-stable-7.jar               | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJA | bdlib                             | 1.14.3.12            | bdlib-1.14.3.12-mc1.12.2.jar                       | None                                     |
	| LCHIJA | ae2stuff                          | 0.7.0.4              | ae2stuff-0.7.0.4-mc1.12.2.jar                      | None                                     |
	| LCHIJA | aroma1997core                     | 2.0.0.2.b167         | aroma1997core-1.12.2-2.0.0.2.b167.jar              | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCHIJA | baubles                           | 1.5.2                | Baubles_1.12_1.5.2.jar                             | None                                     |
	| LCHIJA | bookshelf                         | 2.3.590              | Bookshelf_1.12.2_2.3.590.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | codechickenlib                    | 3.2.3.358            | codechickenlib-1.12.2-3.2.3.358-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | redstoneflux                      | 2.1.1                | redstoneflux-1.12-2.1.1.1-universal.jar            | None                                     |
	| LCHIJA | brandonscore                      | 2.4.20               | brandonscore-1.12.2-2.4.20.162-universal.jar       | None                                     |
	| LCHIJA | buildcraftlib                     | 7.99.24.8            | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LCHIJA | buildcraftcore                    | 7.99.24.8            | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LCHIJA | buildcraftbuilders                | 7.99.24.8            | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LCHIJA | buildcrafttransport               | 7.99.24.8            | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LCHIJA | buildcraftsilicon                 | 7.99.24.8            | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LCHIJA | crafttweaker                      | 4.1.20               | crafttweaker2-1.12-4.1.20.679.jar                  | None                                     |
	| LCHIJA | ic2                               | 2.8.170-ex112        | industrialcraft-2-2.8.170-ex112.jar                | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | buildcraftcompat                  | 7.99.24.8            | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LCHIJA | buildcraftenergy                  | 7.99.24.8            | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LCHIJA | buildcraftfactory                 | 7.99.24.8            | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LCHIJA | buildcraftrobotics                | 7.99.24.8            | buildcraft-all-7.99.24.8.jar                       | None                                     |
	| LCHIJA | chickenchunks                     | 2.4.2.74             | chickenchunks-1.12.2-2.4.2.74-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | cofhcore                          | 4.6.6                | cofhcore-1.12.2-4.6.6.1-universal.jar              | None                                     |
	| LCHIJA | cofhworld                         | 1.4.0                | cofhworld-1.12.2-1.4.0.1-universal.jar             | None                                     |
	| LCHIJA | jei                               | 4.16.1.302           | jei_1.12.2-4.16.1.302.jar                          | None                                     |
	| LCHIJA | crafttweakerjei                   | 2.0.3                | crafttweaker2-1.12-4.1.20.679.jar                  | None                                     |
	| LCHIJA | cyclicmagic                       | 1.20.12              | Cyclic-1.12.2-1.20.13.jar                          | 0e5cb559be7d03f3fc18b8cba547d663e25f28af |
	| LCHIJA | thermalfoundation                 | 2.6.7                | thermalfoundation-1.12.2-2.6.7.1-universal.jar     | None                                     |
	| LCHIJA | draconicevolution                 | 2.3.28               | draconic-evolution-1.12.2-2.3.28.354-universal.jar | None                                     |
	| LCHIJA | elevatorid                        | 1.3.14               | ElevatorMod_1.12.2_1.3.14.jar                      | None                                     |
	| LCHIJA | eplus                             | 5.0.179              | enchantingplus-1.12.2-5.0.179.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | endercore                         | 1.12.2-0.5.76        | EnderCore-1.12.2-0.5.76.jar                        | None                                     |
	| LCHIJA | endercrop                         | 1.12-1.3.4           | endercrop_1.12_1.3.4.jar                           | None                                     |
	| LCHIJA | thermalexpansion                  | 5.5.7                | thermalexpansion-1.12.2-5.5.7.1-universal.jar      | None                                     |
	| LCHIJA | enderio                           | 5.3.70               | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCHIJA | enderiointegrationtic             | 5.3.70               | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCHIJA | enderiobase                       | 5.3.70               | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCHIJA | enderioconduits                   | 5.3.70               | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCHIJA | enderioconduitsappliedenergistics | 5.3.70               | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCHIJA | enderioconduitsopencomputers      | 5.3.70               | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCHIJA | enderioconduitsrefinedstorage     | 5.3.70               | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCHIJA | enderiointegrationforestry        | 5.3.70               | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCHIJA | enderiointegrationticlate         | 5.3.70               | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCHIJA | enderioinvpanel                   | 5.3.70               | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCHIJA | ftblib                            | 5.4.3.149            | FTBLib-1.12.2-5.4.3.149.jar                        | None                                     |
	| LCHIJA | enderiomachines                   | 5.3.70               | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCHIJA | enderiopowertools                 | 5.3.70               | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCHIJA | enderstorage                      | 2.4.6.137            | enderstorage-1.12.2-2.4.6.137-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | equip                             | 1.1                  | Equip_6564_1.12.2_1.1.jar                          | None                                     |
	| LCHIJA | gunpowderlib                      | 1.12.2-1.1           | gunpowderlib-1.12.2-1.1.jar                        | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
	| LCHIJA | twilightforest                    | 3.11.1021            | twilightforest_1.12.2_3.11.1021_universal.jar      | None                                     |
	| LCHIJA | immersiveengineering              | 0.12-98              | ImmersiveEngineering_0.12_98.jar                   | None                                     |
	| LCHIJA | exchangers                        | 1.12.2-2.10.2        | exchangers-1.12.2-2.10.2.jar                       | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
	| LCHIJA | fastleafdecay                     | v14                  | fastleafdecay-v14.jar                              | None                                     |
	| LCHIJA | fluxnetworks                      | 4.1.0                | fluxnetworks-1.12.2-4.1.1.34.jar                   | None                                     |
	| LCHIJA | forgemultipartcbe                 | 2.6.0.79             | forge-multipart-1_12_2.jar                         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | microblockcbe                     | 2.6.0.79             | forge-multipart-1_12_2.jar                         | None                                     |
	| LCHIJA | minecraftmultipartcbe             | 2.6.0.79             | forge-multipart-1_12_2.jar                         | None                                     |
	| LCHIJA | gravisuite                        | 3.1.1                | gravitationsuite-3.1.1.jar                         | None                                     |
	| LCHIJA | guideapi                          | 1.12-2.1.8-63        | Guide-API-1.12-2.1.8-63.jar                        | None                                     |
	| LCHIJA | hammercore                        | 2.0.6.32             | hammerlib-1.12.2-2.0.6.32.jar                      | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LCHIJA | waila                             | 1.8.26               | hwyla-1.8.26-b41_1.12.2.jar                        | None                                     |
	| LCHIJA | trackapi                          | 1.2                  | trackapi-1.2-1.12.2.jar                            | None                                     |
	| LCHIJA | universalmodcore                  | 1.1.4                | universalmodcore-1.12.2-forge-1.1.4-2b81e7.jar     | None                                     |
	| LCHIJA | immersiverailroading              | 1.9.1                | ImmersiveRailroading-1.12.2-forge-1.9.1.jar        | None                                     |
	| LCHIJA | inventorytweaks                   | 1.64+dev.151.822d839 | inventorytweaks-1.64dev.151.jar                    | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | ironchest                         | 1.12.2-7.0.67.844    | ironchest-1.12.2-7.0.72.847.jar                    | None                                     |
	| LCHIJA | journeymap                        | 1.12.2-5.7.1         | journeymap-1.12.2-5.7.1.jar                        | None                                     |
	| LCHIJA | medieval_craft                    | 1.14.4               | MedievalCraft-1.12.2-1.18.1.jar                    | None                                     |
	| LCHIJA | millenaire                        | Millénaire 8.1.2     | millenaire-8.1.2-1.12.2.jar                        | None                                     |
	| LCHIJA | llibrary                          | 1.7.20               | llibrary_1.7.20_1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | mowziesmobs                       | 1.5.8                | mowziesmobs_1.12.2_1.5.8.jar                       | None                                     |
	| LCHIJA | reap                              | 1.5.3                | reap-1.5.3.jar                                     | None                                     |
	| LCHIJA | solarflux                         | 12.4.11              | solarfluxreborn-1.12.2-12.4.11.jar                 | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LCHIJA | tatw                              | 1.0.1.2.b27          | tatw-1.12.2-1.0.1.2.b27.jar                        | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCHIJA | thermaldynamics                   | 2.5.6                | thermaldynamics-1.12.2-2.5.6.1-universal.jar       | None                                     |
	| LCHIJA | torcherino                        | 7.5                  | torcherino_1.12.2_7.5.jar                          | None                                     |
	| LCHIJA | veinminer                         | 0.38.2               | veinminer-1.12-0.38.2.647b31535a.jar               | None                                     |
	| LCHIJA | veinminermodsupport               | 0.38.2               | veinminer-1.12-0.38.2.647b31535a.jar               | None                                     |
	| LCHIJA | wanionlib                         | 1.12.2-2.9           | wanionlib-1.12.2-2.9.jar                           | None                                     |
	| LCHIJA | wrcbe                             | 2.3.2                | WR-CBE-1.12.2-2.3.2.33-universal.jar               | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | yabba                             | 1.1.2.54             | YABBA-1.12.2-1.1.2.54.jar                          | None                                     |
	| LCHIJA | rebornmod                         | 1.1.2                | JurassicWorldReborn-1.12.2-1.2.0.jar               | None                                     |
	| LCHIJA | unidict                           | 1.12.2-3.0.10        | unidict-1.12.2-3.0.10.jar                          | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
Inventory Tweaks Coremod (inventorytweaks-1.64dev.151.jar)
  invtweaks.forge.asm.ContainerTransformer
CTMCorePlugin (ctm-mc1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
CoreMod (aroma1997core-1.12.2-2.0.0.2.b167.jar)
  
UniDictCoreMod (unidict-1.12.2-3.0.10.jar)
  wanion.unidict.core.UniDictCoreModTransformer
HCASM (hammerlib-1.12.2-2.0.6.32.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Offline mode for dedicated servers is NOT supported by Ender IO.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Authlib is : /F:/Games/Minecraft/Server_TestCraft_1.12.2_forge_magma/libraries/minecraft_server.1.12.2.jar

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	HammerCore Debug Information: 
		Dependent Mods: None.

	List of loaded APIs: 
		* appliedenergistics2|API (rv6) from appliedenergistics2-rv6-stable-7.jar
		* Baubles|API (1.4.0.2) from Baubles_1.12_1.5.2.jar
		* buildcraftapi_blocks (1.0) from buildcraft-all-7.99.24.8.jar
		* buildcraftapi_boards (2.0) from buildcraft-all-7.99.24.8.jar
		* buildcraftapi_core (2.2) from buildcraft-all-7.99.24.8.jar
		* buildcraftapi_crops (1.1) from buildcraft-all-7.99.24.8.jar
		* buildcraftapi_enums (1.0) from buildcraft-all-7.99.24.8.jar
		* buildcraftapi_events (2.0) from buildcraft-all-7.99.24.8.jar
		* buildcraftapi_facades (1.1) from buildcraft-all-7.99.24.8.jar
		* buildcraftapi_filler (5.0) from buildcraft-all-7.99.24.8.jar
		* buildcraftapi_fuels (2.0) from buildcraft-all-7.99.24.8.jar
		* buildcraftapi_gates (4.1) from buildcraft-all-7.99.24.8.jar
		* buildcraftapi_items (1.1) from buildcraft-all-7.99.24.8.jar
		* buildcraftapi_library (2.0) from buildcraft-all-7.99.24.8.jar
		* buildcraftapi_lists (1.0) from buildcraft-all-7.99.24.8.jar
		* buildcraftapi_power (1.3) from buildcraft-all-7.99.24.8.jar
		* buildcraftapi_recipes (3.0) from buildcraft-all-7.99.24.8.jar
		* buildcraftapi_robotics (3.0) from buildcraft-all-7.99.24.8.jar
		* buildcraftapi_statements (1.1) from buildcraft-all-7.99.24.8.jar
		* buildcraftapi_tiles (1.2) from buildcraft-all-7.99.24.8.jar
		* buildcraftapi_tools (1.0) from buildcraft-all-7.99.24.8.jar
		* buildcraftapi_transport (5.0) from buildcraft-all-7.99.24.8.jar
		* cofhapi (2.5.0) from cofhcore-1.12.2-4.6.6.1-universal.jar
		* ctm-api (0.1.0) from ctm-mc1.12.2-1.0.2.31.jar
		* ctm-api-events (0.1.0) from ctm-mc1.12.2-1.0.2.31.jar
		* ctm-api-models (0.1.0) from ctm-mc1.12.2-1.0.2.31.jar
		* ctm-api-textures (0.1.0) from ctm-mc1.12.2-1.0.2.31.jar
		* ctm-api-utils (0.1.0) from ctm-mc1.12.2-1.0.2.31.jar
		* DraconicEvolution|API (1.3) from draconic-evolution-1.12.2-2.3.28.354-universal.jar
		* enderioapi (4.0.0) from EnderIO-1.12.2-5.3.70.jar
		* enderioapi|addon (4.0.0) from EnderIO-1.12.2-5.3.70.jar
		* enderioapi|capacitor (4.0.0) from EnderIO-1.12.2-5.3.70.jar
		* enderioapi|conduits (4.0.0) from EnderIO-1.12.2-5.3.70.jar
		* enderioapi|farm (4.0.0) from EnderIO-1.12.2-5.3.70.jar
		* enderioapi|redstone (4.0.0) from EnderIO-1.12.2-5.3.70.jar
		* enderioapi|teleport (4.0.0) from EnderIO-1.12.2-5.3.70.jar
		* enderioapi|tools (4.0.0) from EnderIO-1.12.2-5.3.70.jar
		* enderioapi|upgrades (4.0.0) from EnderIO-1.12.2-5.3.70.jar
		* Guide-API|API (2.0.0) from Guide-API-1.12-2.1.8-63.jar
		* ImmersiveEngineering|API (1.0) from ImmersiveEngineering_0.12_98.jar
		* ImmersiveEngineering|ImmersiveFluxAPI (1.0) from ImmersiveEngineering_0.12_98.jar
		* journeymap|client-api (1.4) from journeymap-1.12.2-5.7.1.jar
		* journeymap|client-api-display (1.4) from journeymap-1.12.2-5.7.1.jar
		* journeymap|client-api-event (1.4) from journeymap-1.12.2-5.7.1.jar
		* journeymap|client-api-model (1.4) from journeymap-1.12.2-5.7.1.jar
		* journeymap|client-api-util (1.4) from journeymap-1.12.2-5.7.1.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.16.1.302.jar
		* redstonefluxapi (2.1.1) from redstoneflux-1.12-2.1.1.1-universal.jar
		* veinminerApi (0.3) from veinminer-1.12-0.38.2.647b31535a.jar
		* WailaAPI (1.3) from hwyla-1.8.26-b41_1.12.2.jar
	AE2 Integration: IC2:ON, RC:OFF, MFR:OFF, Waila:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:ON
	Profiler Position: N/A (disabled)
	Player Count: 1 / 99; [EntityPlayerMP['Test'/755, uuid='beb5d4c7-781c-3b1f-89bc-f9e5f467a1d6', l='Test_World', x=3141.71, y=64.00, z=6.81, cx=196, cd=0, tl=2943419, v=true, d=false](Test at 3141.713263661995,64.0,6.812398196834397)]
	Is Modded: Definitely; Server brand changed to 'Magma'
	Type: Dedicated Server (map_server.txt)
```

**Comment by m2d2411** [comment]
same thing happened to me just with the feeders, Gallimimuses and the dodos
